package resource;

import java.util.HashMap;
import java.util.Map;



public class Constants {
	public enum RoleType{Null,Deploy,TesterVersion,DeveloperVersion,Developer,DeveloperManager,Tester,Admin,Auditor;}
	private static final  Map<String, String> StringConstans=new HashMap<String, String>();
	static 
	{
		//菜单中文
		StringConstans.put("menu_file_zh", "文件");
		StringConstans.put("menu_group_zh", "应用系统");
		StringConstans.put("menu_help_zh", "帮助");
		StringConstans.put("menuitem_file_openvzip_zh", "打开版本包");
		StringConstans.put("menuitem_file_saveAs_zh", "另存为");
		StringConstans.put("menuitem_file_close_zh", "关闭");
		StringConstans.put("menuitem_file_closeAll_zh", "关闭所有");
		StringConstans.put("menuitem_file_exit_zh", "退出");
		StringConstans.put("menuitem_edit_node_zh", "编辑属性");
		StringConstans.put("menuitem_view_run_zh", "查询执行详情");
		StringConstans.put("menuitem_node_del_zh", "删除");
		StringConstans.put("menuitem_hide_ver_zh", "关闭版本包");
		StringConstans.put("menuitem_cfg_version_zh", "配置运行信息");
		StringConstans.put("menuitem_manual_zh", "使用手册");
		StringConstans.put("menuitem_about_zh", "关于");
		StringConstans.put("menuitem_version_zh", "版本详情");
		StringConstans.put("menuitem_cmpversion_zh", "与另一个版本进行比较");
		//按钮提示文本
		StringConstans.put("btn_tips_ftp_zh", "ftp工具");
		StringConstans.put("btn_tips_share_zh", "共享目录管理工具");
		StringConstans.put("btn_tips_user_zh", "操作员信息");
		StringConstans.put("btn_tips_setting_zh", "设置");
		StringConstans.put("btn_tips_helpversion_zh", "版本检查安装更新");
		StringConstans.put("btn_tips_installversion_zh", "下载安装最新版本");
		StringConstans.put("btn_tips_mapset_zh", "目录映射关系设置");
		StringConstans.put("btn_tips_loading_zh", "加载文件");
		StringConstans.put("btn_tips_compare_zh", "版本升级文件比对清单");
		StringConstans.put("btn_tips_group_zh", "新增节点群组");
		StringConstans.put("btn_tips_adddir_zh", "新增目录");
		StringConstans.put("btn_tips_deldir_zh", "删除目录");
		StringConstans.put("btn_tips_groupmanager_zh", "系统节点管理");
		StringConstans.put("btn_tips_userrole_zh", "用户角色管理");
		StringConstans.put("btn_tips_usergroup_zh", "用户群组管理");
		StringConstans.put("btn_tips_groupmng_zh", "群组管理");
		StringConstans.put("btn_tips_appmng_zh", "应用管理");
		StringConstans.put("btn_tips_report_zh", "升级报告");
		StringConstans.put("btn_tips_start_zh", "启动");
		StringConstans.put("btn_tips_passwd_zh", "密码管理");
		StringConstans.put("btn_tips_approve_zh", "我的审批");
		StringConstans.put("btn_tips_settingmng_zh", "参数管理");
		StringConstans.put("btn_tips_todoList_zh", "我的部署任务");
		StringConstans.put("btn_tips_audit_zh", "操作审计");
		StringConstans.put("btn_tips_auditcheck_zh", "记录搜索");
		StringConstans.put("btn_tips_cfgmng_zh", "配置管理");
		StringConstans.put("btn_tips_addReq_zh", "新增需求与变更");
		StringConstans.put("btn_tips_findReq_zh", "需求搜索");
		StringConstans.put("btn_tips_question_zh", "问题管理");
		StringConstans.put("btn_tips_localnode_zh", "节点管理");
		StringConstans.put("btn_tips_findByPath_zh", "根据绝对路径搜索文件");
		StringConstans.put("btn_tips_viewdetail_zh", "编辑/查看详情……");
		StringConstans.put("table_tips_candragfile_zh", "可从文件浏览器拖拽文件(编辑状态下)");
		
		
		StringConstans.put("btn_tips_installcheck_zh", "安装复核");
		StringConstans.put("btn_tips_statistic_zh", "统计报表");
		StringConstans.put("btn_tips_addnodedb_zh", "添加数据库节点");
		StringConstans.put("btn_tips_addnodebp_zh", "添加节点");
		StringConstans.put("btn_tips_delnode_zh", "删除节点");
		StringConstans.put("btn_tips_connode_zh", "连接节点");
		StringConstans.put("btn_tips_importpkg_zh", "导入版本包");
		StringConstans.put("btn_tips_versionation_zh", "开始安装版本包");
		StringConstans.put("btn_tips_manual_zh", "用户使用手册");
		StringConstans.put("btn_tips_about_zh", "关于");
		StringConstans.put("text_tips_ip_zh", "必输项，请输入合法的ip否则无法通过校验");
		StringConstans.put("text_tips_dbobj_zh", "数据库对象名");
		StringConstans.put("text_tips_ftpuser_zh", "必输项，登陆Sftp服务使用的用户");
		StringConstans.put("text_tips_ftppasswd_zh", "必输项，Sftp服务使用的用户密码");
		StringConstans.put("text_tips_shareduser_zh", "必输项，使用共享目录上传版本时，需要共享目录的域用户名称");
		StringConstans.put("text_tips_sharedpasswd_zh", "必输项，使用共享目录上传版本时，需要共享目录的域用户密码");
		StringConstans.put("text_tips_ftpdir_zh", "必输项，Sftp服务站点的根目录");
		StringConstans.put("text_tips_sambadir_zh", "必输项，共享目录起始目录");
		StringConstans.put("text_tips_nodename_zh", "必输项，标识节点方便识别 如：核心1数据库，总控KCBP等");
		StringConstans.put("text_tips_configname_zh", "配置文件名称，如果有同名文件，文件名称请带上相对路径");
		StringConstans.put("text_tips_nodedesc_zh", "非必输项，Windows操作系统节点可指定VService服务端口号");
		StringConstans.put("text_tips_nodegroup_zh", "必输项，节点群组可以选择一个或多个");
		StringConstans.put("text_tips_viewnodegroup_zh", "浏览群组标签");
		StringConstans.put("text_tips_uploaddir_zh", "必输项，共享目录方式请指定共享目录下的某个目录,不存在会自动建立，使用完整相对路径方式(如：共享目录为temp,版本上传目录可以填写temp/version)\r\nFTP方式请指定一个ftp站点主目录下的路径，需要使用相对路径 如versions\\data");
		StringConstans.put("text_tips_backdir_zh", "数据库节点的备份目录必须指定绝对路径，必须是远程节点机器已经存在的目录\r\n中间件节点非必输，不指定备份目录，会自动在工具的工作目录下创建");
		StringConstans.put("text_tips_dbuser_zh", "必输项，sqlCmd登陆数据库执行脚本时需要使用");
		StringConstans.put("text_tips_dbname_zh", "必输项，备份数据库时需要使用，多个数据库名称使用逗号(如run,ctl)分开");
		StringConstans.put("text_tips_backdbname_zh", "备份数据库的库名");
		StringConstans.put("text_tips_dbpasswd_zh", "必输项，sqlCmd登陆数据库执行脚本时需要使用");
		StringConstans.put("text_tips_dbport_zh", "必输项，建立数据库连接使用的端口号");
		StringConstans.put("text_tips_lbmdir_zh", "必输项，填写lbm的绝对路径 如：****\\lbm");
		StringConstans.put("text_tips_bindir_zh", "必输项，填写bin目录的绝对路径 如：****\\bin");
		StringConstans.put("text_tips_nodeseq_zh", "必输项，同一个核心内的节点序号必须唯一指定");
		StringConstans.put("text_tips_start_zh", "必输项,填写启动KCBP启动bat脚本的绝对路径");
		StringConstans.put("text_tips_stop_zh", "必输项,填写停止KCBP启动bat脚本的绝对路径");
		StringConstans.put("text_tips_remeber_zh", "记住密码后可自动登陆");
		StringConstans.put("text_tips_switchuser_zh", "用户多角色切换");
		StringConstans.put("btn_tips_addstream_zh", "新建流");
		StringConstans.put("btn_tips_add_zh", "新建");
		StringConstans.put("btn_tips_open_zh", "打开");
		StringConstans.put("btn_tips_refreshstream_zh", "同步流");
		StringConstans.put("btn_tips_addrelease_zh", "新增发布");
		StringConstans.put("btn_tips_refreshrelease_zh", "刷新发布");
		StringConstans.put("btn_tips_refreshReq_zh", "刷新需求");
		StringConstans.put("btn_tips_filterReq_zh", "筛选需求");
		StringConstans.put("btn_tips_versiondir_zh", "版本目录设置");
		StringConstans.put("btn_tips_dbbackup_zh", "备份数据库对象");
		StringConstans.put("btn_tips_nextoperator_zh", "设置下一个处理人");
		StringConstans.put("btn_tips_showClosed_zh", "显示关闭对象");
		StringConstans.put("btn_tips_hideClosed_zh", "隐藏关闭对象");
		StringConstans.put("text_tips_rootdir_zh", "安装组件的主目录或根目录");
		StringConstans.put("btn_tips_adduser_zh", "新增用户");
		StringConstans.put("btn_tips_addcfg_zh", "新增配置项");
		StringConstans.put("btn_tips_searchfile_zh", "根据路径在指定文件夹搜索");
		StringConstans.put("text_tips_timespan_zh", "自动部署版本的时间。格式为：16：00-08：00");
		
		StringConstans.put("cbo_tips_searchreq_zh", "输入需求关键字可进行模糊搜索");
		//按钮文本
		StringConstans.put("btn_apply_zh", "应用");
		StringConstans.put("btn_ok_zh", "确认");
		StringConstans.put("btn_finalok_zh", "最终确认");
		StringConstans.put("btn_cancel_zh", "取消");
		StringConstans.put("btn_redo_zh", "重新执行");
		StringConstans.put("btn_skip_zh", "跳过执行");
		StringConstans.put("btn_service_zh", "执行服务");
		StringConstans.put("btn_make_zh", "制作版本");
		StringConstans.put("btn_query_zh", "查询");
		StringConstans.put("btn_export_zh", "导出");
		StringConstans.put("btn_enable_zh", "启动运行");
		StringConstans.put("btn_install_zh", "启动部署");
		StringConstans.put("btn_goonInstall_zh", "恢复部署");
		StringConstans.put("btn_active_zh", "激活");
		StringConstans.put("btn_review_zh", "提交复核");
		StringConstans.put("btn_update_zh", "修改");
		StringConstans.put("btn_delete_zh", "删除");
		StringConstans.put("btn_deleterole_zh", "移除用户角色");
		StringConstans.put("btn_deletegroup_zh", "移除用户群组");
		StringConstans.put("btn_up_zh", "上移");
		StringConstans.put("btn_down_zh", "下移");
		StringConstans.put("btn_setboot_zh", "设为引导脚本");
		StringConstans.put("btn_unsetboot_zh", "取消引导");
		StringConstans.put("btn_backup_zh", "备份");
		StringConstans.put("btn_service_zh", "启停服务");
		StringConstans.put("btn_add_zh", "新增");
		StringConstans.put("btn_chooseAll_zh", "全选/反选");
		StringConstans.put("btn_cfgdb_zh", "仅选择数据库");
		StringConstans.put("btn_cfgmid_zh", "仅选择中间件");
		StringConstans.put("btn_remeberpasswd_zh", "记住密码");
		StringConstans.put("btn_login_zh", "登录");
		StringConstans.put("btn_approveOK_zh", "同意");
		StringConstans.put("btn_approveNot_zh", "驳回");
		StringConstans.put("btn_transfer_zh", "转处理");
		StringConstans.put("btn_search_zh", "搜索");
		StringConstans.put("btn_release_zh", "发布");
		StringConstans.put("btn_deploy_zh", "快速部署");
		StringConstans.put("btn_dispatch_zh", "分派");
		StringConstans.put("btn_confirm_zh", "审核确认");
		StringConstans.put("btn_chgstream_zh", "调整归属批次");
		StringConstans.put("btn_download_zh", "下载");
		StringConstans.put("btn_localcmp_zh", "本地比对");
		StringConstans.put("btn_choose_zh", "用户选择");
		StringConstans.put("btn_define_zh", "自定义群组");
		StringConstans.put("btn_showpasswd_zh", "显示密码");
		StringConstans.put("btn_submit_zh", "提交");
		StringConstans.put("btn_agreePkg_zh", "同意发版");
		StringConstans.put("btn_alertPackage_zh", "通知发版");
		StringConstans.put("btn_relatedQuestion_zh", "关联问题");
		StringConstans.put("btn_submitchek_zh", "提交审核");
		StringConstans.put("btn_save_zh", "保存");
		StringConstans.put("btn_more_zh", "更多……");
		StringConstans.put("btn_addreq_zh", "选择待整合需求");
		StringConstans.put("btn_close_zh", "关闭");
		StringConstans.put("btn_resubmit_zh", "重新提交");
		StringConstans.put("btn_left_zh", "遗留后评估");
		StringConstans.put("btn_reply_zh", "答复");
		StringConstans.put("btn_return_zh", "退回");
		StringConstans.put("btn_reset_zh", "重置");
		StringConstans.put("btn_delay_zh", "申请延期");
		//tab页显示名称
		StringConstans.put("tabItem_basic_zh", "基本信息");
		StringConstans.put("tabItem_developer_zh", "开发答复信息");
		StringConstans.put("tabItem_directory_zh", "目录信息");
		StringConstans.put("tabItem_database_zh", "数据库信息");
		StringConstans.put("tabItem_ftp_zh", "FTP信息");
		StringConstans.put("tabItem_sftp_zh", "SFTP信息");
		StringConstans.put("tabItem_samba_zh", "共享目录信息");
		StringConstans.put("tabItem_service_zh", "服务信息");
		
		StringConstans.put("tabItem_steps_zh", "投产步骤浏览器");
		StringConstans.put("tabItem_versions_zh", "版本浏览器");
		StringConstans.put("tabItem_files_zh", "文件浏览器");
		StringConstans.put("tabItem_verdeploy_zh", "版本部署");
		StringConstans.put("tabItem_vermake_zh", "版本制作");
		StringConstans.put("tabItem_release_zh", "发布浏览器");
		StringConstans.put("tabItem_task_zh", "任务浏览器");
		StringConstans.put("tabItem_users_zh", "用户浏览器");
		StringConstans.put("tabItem_appsystem_zh", "应用系统浏览器");
		StringConstans.put("item_add_stream_zh", "新建流");
		StringConstans.put("item_add_release_zh", "新建发布");
		StringConstans.put("tabItem_stream_zh", "批次管理");
		StringConstans.put("tabItem_requirement_zh", "任务浏览器");
		StringConstans.put("tabItem_flowuser_zh", "流程处理人设置");
		StringConstans.put("tabItem_myinstall_zh", "我的版本部署");
		StringConstans.put("tabItem_myapply_zh", "我的申请");
		StringConstans.put("tabItem_mytask_zh", "待我处理");
		StringConstans.put("tabItem_mydone_zh", "我处理过");
		StringConstans.put("tabItem_basicinfo_zh", "基本信息");
		StringConstans.put("tabItem_detailinfo_zh", "详细信息");
		StringConstans.put("tabItem_flowrecord_zh", "过往记录");
		//窗口名称
		StringConstans.put("window_nodeproperty_zh", "节点属性");
		StringConstans.put("window_nodegroup_zh", "节点群组");
		StringConstans.put("window_valid_zh", "产品认证");
		StringConstans.put("window_stepRunNode_zh", "步骤运行节点属性");
		StringConstans.put("window_sysparam_zh", "系统参数");
		StringConstans.put("window_verfilelist_zh", "版本升级文件清单");
		StringConstans.put("window_schedule_zh", "节点调度情况");
		StringConstans.put("window_dbnode_zh", "数据库");
		StringConstans.put("window_appinfo_zh", "应用信息");
		StringConstans.put("window_searchret_zh", "搜索结果");
		StringConstans.put("window_userlogin_zh", "用户登录");
		StringConstans.put("window_passwdset_zh", "密码设置");
		StringConstans.put("window_detail_zh", "详情");
		StringConstans.put("window_userchoose_zh", "用户选择");
		StringConstans.put("window_flowprocess_zh", "流程处理");
		StringConstans.put("window_myquestions_zh", "问题清单");
		StringConstans.put("window_groupdefine_zh", "定义群组");
		StringConstans.put("window_backupcfg_zh", "备份配置");
		StringConstans.put("group_backupdir_zh", "选择需要备份的目录:");
		StringConstans.put("group_backupdb_zh", "备份数据库");
		StringConstans.put("group_servicess_zh", "服务启停");
		StringConstans.put("group_appcmt_zh", "审批意见(*)");
		StringConstans.put("group_comment_zh", "修改意见");
		StringConstans.put("group_basic_zh", "基本信息");
		StringConstans.put("group_qinfo_zh", "问题信息");
		StringConstans.put("group_rinfo_zh", "需求信息");
		StringConstans.put("window_userproperty_zh", "用户属性");
		StringConstans.put("window_servicecfg_zh", "服务配置");
		StringConstans.put("window_cfgproperty_zh", "配置属性");
		StringConstans.put("window_quickdeploy_zh", "快速部署");
		//标签文本
		StringConstans.put("label_ip_zh", "ip地址或域名");
		StringConstans.put("label_node_zh", "节点名称");
		StringConstans.put("label_os_zh", "操作系统");
		StringConstans.put("label_node_desc_zh", "VService端口号");
		StringConstans.put("label_node_group_zh", "群组名称");
		StringConstans.put("label_dir_name_zh", "组件名称");
		StringConstans.put("label_dir_autobackup_zh", "目录自动备份");
		StringConstans.put("label_dir_autoservice_zh", "服务自动启停");
		StringConstans.put("label_db_autobackup_zh", "数据库自动备份");
		StringConstans.put("label_dir_filter_zh", "备份过滤目录");
		StringConstans.put("label_dir_value_zh", "组件根目录");
		StringConstans.put("label_svc_name_zh", "服务名");
		StringConstans.put("label_svc_start_zh", "启动脚本");
		StringConstans.put("label_svc_stop_zh", "停止脚本");
		StringConstans.put("label_upload_dir_zh", "版本上传目录");
		StringConstans.put("label_sn_zh", "产品序列号:");
		StringConstans.put("label_backup_dir_zh", "版本备份目录");
		StringConstans.put("label_dbname_zh", "数据库名称");
		StringConstans.put("label_backdbname_zh", "备份数据库名称");
		StringConstans.put("label_dbtype_zh", "数据库类型");
		StringConstans.put("label_dbuser_zh", "数据库登录用户名");
		StringConstans.put("label_backupfilter_zh", "备份过滤规则");
		StringConstans.put("label_dbpasswd_zh", "数据库密码");
		StringConstans.put("label_dbport_zh", "数据库端口");
		StringConstans.put("label_kcbpbin_dir_zh", "KCBP的bin目录");
		StringConstans.put("label_kcbplbm_dir_zh", "KCBP的lbm目录");
		StringConstans.put("label_kcbpstart_zh", "KCBP启动脚本");
		StringConstans.put("label_kcbpstop_zh", "KCBP停止脚本");
		StringConstans.put("label_ftpuser_zh", "ssh用户名");
		StringConstans.put("label_ftppasswd_zh", "ssh用户密码");
		StringConstans.put("label_ftpdir_zh", "ssh站点主目录");
		StringConstans.put("label_ftpport_zh", "ssh端口号");
		StringConstans.put("label_shareuser_zh", "登陆域用户名");
		StringConstans.put("label_sharepasswd_zh", "登陆域用户密码");
		StringConstans.put("label_sharedir_zh", "共享目录名称(*)");
		StringConstans.put("label_versionDesc_zh", "版本描述(*)");
		StringConstans.put("label_nodecate_zh", "节点类别(*)");
		StringConstans.put("label_nodeseq_zh", "节点序号(*)");
		StringConstans.put("label_namecopyright_zh", "版权所有");
		StringConstans.put("label_valuecopyright_zh", "国信证券信息技术总部");
		StringConstans.put("label_namecontact_zh", "联系信息");
		StringConstans.put("label_valuecontact_zh", "0755-82130833\r\n转701552");
		StringConstans.put("label_nameversion_zh", "当前版本:");
		StringConstans.put("label_newversion_zh", "软件最新版本:");
		StringConstans.put("label_versiondesc_zh", "版本说明:");
		StringConstans.put("label_user_zh", "登录用户名");
		StringConstans.put("label_passwd_zh", "登录密码");
		StringConstans.put("label_surepasswd_zh", "确认密码");
		StringConstans.put("label_name_zh", "名称(*)");
		StringConstans.put("label_streamname_zh", "归属流(*)");
		StringConstans.put("label_desc_zh", "描述:");
		StringConstans.put("label_descattach_zh", "沟通纪要:");
		StringConstans.put("label_mdfuser_zh", "维护人");
		StringConstans.put("label_mdftime_zh", "维护时间");
		StringConstans.put("label_version_zh", "版本");
		StringConstans.put("label_nextUser_zh", "下一处理人");
		StringConstans.put("label_list_zh", "发布清单:");
		StringConstans.put("label_appname_zh", "应用:");
		StringConstans.put("label_svcstop_zh", "安装**前停止服务");
		StringConstans.put("label_svcstart_zh", "安装**后启动服务");
		StringConstans.put("label_pkgname_zh", "版本号:");
		StringConstans.put("label_rootdir_zh", "安装组件根目录：");
		StringConstans.put("Label_dftRole_zh", "默认角色");
		StringConstans.put("Label_dftGroup_zh", "默认群组");
		StringConstans.put("label_operator_zh", "操作人");
		StringConstans.put("label_tgtIp_zh", "目标ip");
		StringConstans.put("label_datadate_zh", "操作日期");
		StringConstans.put("label_delaydate_zh", "延期到:");
		StringConstans.put("label_reason_zh", "理由说明:");
		/////////////////////////////////////////////////////////////////
		StringConstans.put("label_taskno_zh", "任务编号:");
		StringConstans.put("label_taskname_zh", "任务名称:");
		StringConstans.put("label_taskapp_zh", "应用:");
		StringConstans.put("label_taskrdate_zh", "预期上线时间:");
		StringConstans.put("label_taskcrt_zh", "分派人:");
		StringConstans.put("label_taskadate_zh", "预期开发完成时间:");
		StringConstans.put("label_taskddate_zh", "开发完成时间:");
		StringConstans.put("label_taskowner_zh", "责任人:");
		StringConstans.put("label_taskdowner_zh", "开发责任人");
		StringConstans.put("label_taskddate_zh", "开发完成时间:");
		StringConstans.put("label_taskbatch_zh", "批次:");
		StringConstans.put("label_taskstatus_zh", "状态:");
		/////////////////////////////////////////////////////////////////
		StringConstans.put("label_reqno_zh", "需求编号:");
		StringConstans.put("label_reqtitle_zh", "需求标题:");
		StringConstans.put("label_reqsuer_zh", "提出人:");
		StringConstans.put("label_reqdept_zh", "部门:");
		StringConstans.put("label_reqsdate_zh", "提出时间:");
		StringConstans.put("label_reqbk_zh", "需求背景:");
		StringConstans.put("label_reqrdesc_zh", "期望功能:");
		StringConstans.put("label_reqrdate_zh", "预计上线时间:");
		StringConstans.put("label_reqsrouce_zh", "来源:");
		StringConstans.put("label_reqtype_zh", "类型:");
		StringConstans.put("label_reqLevel_zh", "紧急程度:");
		StringConstans.put("label_reqStatus_zh", "状态:");
		StringConstans.put("label_reqlink_zh", "链接:");
		StringConstans.put("label_reqAttach_zh", "附件:");
		/////////////////////////////////////
		StringConstans.put("label_streamStart_zh", "开始时间:");
		StringConstans.put("label_streamEnd_zh", "结束时间:");
		//////////////////////////////////////////////////////////////
		StringConstans.put("label_appclass_zh", "系统分类:");
		StringConstans.put("label_appsclass_zh", "关联系统:");
		StringConstans.put("label_reqdesc_zh", "需求描述:");
		StringConstans.put("label_duedate_zh", "计划截止日期:");
		
		StringConstans.put("label_relUses_zh", "相关人员:");
		StringConstans.put("label_checkUses_zh", "代码审核人:");
		StringConstans.put("label_resolveDesc_zh", "解决方案描述:(*)");
		StringConstans.put("label_fileList_zh", "修改文件和脚本列表:(*)\r\n(版本管理员更新依据)");
		StringConstans.put("label_source_zh", "补丁源码:");
		StringConstans.put("label_compileFiles_zh", "                    发布文件(*):\r\n(含编译文件,脚本,存储过程)");
		StringConstans.put("label_impactDesc_zh", "影响范围补充说明:");
		StringConstans.put("label_submitDesc_zh", "提交说明:");
		StringConstans.put("label_editDesc_zh", "发版说明(*):");
		StringConstans.put("label_testSuggestDesc_zh", "测试建议说明:");
		StringConstans.put("label_selfTestDesc_zh", "自测说明:");
		StringConstans.put("label_testcaseDesc_zh", "功能测试案例:");
		StringConstans.put("label_codeCheck_zh", "代码评审:");
		StringConstans.put("label_solutionCheck_zh", "方案评审:");
		///////////////////////////////////////////////////////////////////////////////
		StringConstans.put("label_nextProcess_zh", "下一处理：");
		StringConstans.put("label_processor_zh", "处理人：");
		StringConstans.put("label_qid_zh", "问题编号:");
		StringConstans.put("label_suser_zh", "问题提出人:");
		StringConstans.put("label_stime_zh", "提出时间:");
		StringConstans.put("label_qclass_zh", "问题分类:");
		StringConstans.put("label_qstatus_zh", "问题状态:");
		StringConstans.put("label_qreq_zh", "项目需求:");
		StringConstans.put("label_qown_zh", "问题所属人:");
		StringConstans.put("label_qdesc_zh", "问题描述:");
		StringConstans.put("label_qatta_zh", "问题附件:");
		StringConstans.put("label_qddesc_zh", "修改描述:");
		StringConstans.put("label_qdatta_zh", "答复附件:");
		//表格表头
		StringConstans.put("header_version_zh", "版本名称");
		StringConstans.put("header_name_zh", "文件名称");
		StringConstans.put("header_oldmd5_zh", "安装前MD5");
		StringConstans.put("header_md5_zh", "安装后MD5");
		StringConstans.put("header_result_zh", "比对结果");
		StringConstans.put("header_path_zh", "文件路径");
		StringConstans.put("header_seq_zh", "序号");
		StringConstans.put("header_action_zh", "操作");
		StringConstans.put("header_group_zh", "系统名称");
		StringConstans.put("header_installstatus_zh", "部署状态");
		StringConstans.put("header_node_zh", "节点名称");
		StringConstans.put("header_path_zh", "目标路径");
		StringConstans.put("header_dir_zh", "目录名称");
		StringConstans.put("header_file_zh", "文件个数");
		StringConstans.put("header_bin_zh", "KCBP/bin文件个数");
		StringConstans.put("header_lbm_zh", "KCBP/lbm文件个数");
		StringConstans.put("header_db_zh", "数据库脚本个数");
		StringConstans.put("header_ddl_zh", "DDL个数");
		StringConstans.put("header_data_zh", "DATA个数");
		StringConstans.put("header_proc_zh", "PROC个数");
		StringConstans.put("header_status_zh", "执行状态");
		StringConstans.put("header_retresult_zh", "执行结果");
		StringConstans.put("header_time_zh", "执行时间");
		StringConstans.put("header_ip_zh", "IP地址");
		StringConstans.put("header_filename_zh", "文件名");
		StringConstans.put("header_mdfdate_zh", "修改时间");
		StringConstans.put("header_crtdate_zh", "创建时间");
		StringConstans.put("header_md5_zh", "识别码");
		StringConstans.put("header_approveID_zh", "审批编号");
		StringConstans.put("header_flowid_zh", "流程编号");
		StringConstans.put("header_funcid_zh", "功能编号");
		StringConstans.put("header_flowstatus_zh", "流程状态");
		StringConstans.put("header_flowname_zh", "流程");
		StringConstans.put("header_stepname_zh", "当前处理");
		StringConstans.put("header_applytime_zh", "提交时间");
		StringConstans.put("header_approveStatus_zh", "处理状态");
		StringConstans.put("header_currentUser_zh", "处理人");
		StringConstans.put("header_applyUser_zh", "申请人");
		StringConstans.put("header_flowdetail_zh", "详情");
		StringConstans.put("header_processTime_zh", "处理时间");
		StringConstans.put("header_processcmt_zh", "处理意见");
		StringConstans.put("header_userID_zh", "用户编号");
		StringConstans.put("header_userName_zh", "姓名");
		StringConstans.put("header_userEmail_zh", "邮箱");
		StringConstans.put("header_userPhone_zh", "电话");
		StringConstans.put("header_userStatus_zh", "状态");
		StringConstans.put("header_userApps_zh", "应用");
		StringConstans.put("header_userAppsys_zh", "系统简称");
		StringConstans.put("header_appSysname_zh", "系统名称");
		StringConstans.put("header_enable_zh", "是否启用");
		StringConstans.put("header_timespan_zh", "版本部署时间区间");
		StringConstans.put("header_tgtnode_zh", "目标节点");
		StringConstans.put("header_operuser_zh", "操作用户");
		StringConstans.put("header_operterm_zh", "用户终端");
		StringConstans.put("header_opertime_zh", "访问时间");
		StringConstans.put("header_approverType_zh", "审批人类型");
		StringConstans.put("header_approverobj_zh", "审批人编号");
		StringConstans.put("header_appname_zh", "应用");
		StringConstans.put("header_environment_zh", "环境类型");
		StringConstans.put("header_configfile_zh", "配置文件");
		StringConstans.put("header_variable_zh", "变量");
		StringConstans.put("header_value_zh", "值");
		StringConstans.put("header_crtUser_zh", "创建人");
		StringConstans.put("header_reqsno_zh", "需求序号");
		StringConstans.put("header_reqstatus_zh", "状态");
		StringConstans.put("header_reqsystem_zh", "系统分类");
		StringConstans.put("header_reqprocessor_zh", "当前处理人");
		StringConstans.put("header_submituser_zh", "提交人");
		//树标签
		//提示标题
		StringConstans.put("messagebox_alert_zh", "温馨提示");
		StringConstans.put("messagebox_installalert_zh", "确认版本安装");
		StringConstans.put("messagebox_import_zh", "确认版本已经导入");
		StringConstans.put("messagebox_replaceFile_zh", "文件替换");
		//提示内容
		StringConstans.put("alert_necessaryinput_zh", "必输字段未输入或超长。请检查并输入完整！");
		StringConstans.put("alert_necessarychoose_zh", "请选择！");
		StringConstans.put("alert_successoperate_zh", "操作成功！");
		StringConstans.put("alert_config_zh", "确认所有配置完整，可以安装版本？");
		StringConstans.put("alert_import_zh", "请确认有成功导入版本包，才可以启动安装版本");
		StringConstans.put("alert_install_zh", "版本不能重复安装或直接安装，需要先进行导入！");
		StringConstans.put("alert_errorformat_zh", "输入的格式不合法！");
		StringConstans.put("alert_busy_zh", "正在进行当前版本包处理，请耐心等待！");
		StringConstans.put("alert_select_zh", "请选择进入人工接管(执行中断)的步骤！");
		StringConstans.put("alert_filechoose_zh", "请先选中需要制作版本的文件！");
		StringConstans.put("alert_successed_zh", "成功生成版本包到您的工作目录！");
		StringConstans.put("alert_failed_zh", "生成版本包出错！，详见错误日志。");
		StringConstans.put("alert_upload_zh", "FTP上传版本包出错！");
		StringConstans.put("alert_timezone_zh", "当前时间不在系统可运行区间，不能安装版本，详见参数设置！");
		StringConstans.put("alert_duplicateval_zh", "重复的值或已经存在的值，请重新指定！");
		StringConstans.put("alert_nopkgsystem_zh", "没有系统有待安装的版本！");
		StringConstans.put("alert_errorformat_zh", "错误的格式！");
		StringConstans.put("alert_agentIntall_zh", "Windows非数据库机器节点需要下载VService才能自动部署(https://pan.guosen.com.cn/l/yo7MtM)！");
		
		//树根名称
		StringConstans.put("treeitem_lbm_zh", "KCBP/lbm目录");
		StringConstans.put("treeitem_bin_zh", "KCBP/bin目录");
		StringConstans.put("treeitem_database_zh", "database");
		StringConstans.put("treeitem_doc_zh", "其它");
		StringConstans.put("treeitem_dbnode_zh", "数据库节点");
		StringConstans.put("treeitem_midnode_zh", "中间件节点");
		StringConstans.put("treeitem_allnode_zh", "所有节点");
		StringConstans.put("treeitem_dirversion_zh", "版本目录");
		//GROUP名称
		StringConstans.put("group_ftp_zh", "SSH登陆信息设置");
		StringConstans.put("group_db_zh", "数据库登陆信息设置");
		StringConstans.put("group_nodegroup_zh", "节点群组管理");
		StringConstans.put("group_sharedir_zh", "共享目录信息设置");
		//
		StringConstans.put("link_forgetpasswd_zh", "忘记密码？");
	}
	
	public static String getStringVaule(String name){
			String variable=name+"_"+Context.Language;
		return Constants.StringConstans.get(variable);
	}
	
	public static final int  sizeCanvasWidth=100*30; 
	public static final int  sizeCanvasHeigth=100*15;
	public static final int  sizeShapeHeight=108; 
	public static final int  sizeShapeWidth=100; 
	public static final int  sizeRectangleShapeHeight=64;
	public static final int  sizeRectangleShapeWidth=64;
	
	public static final String defaultSftpDir="/home/VService/workDir";
	public static final String StepUpload="$UPLOAD";
	public static  String backVersionDir="@base"+"/backup/@nodeid/@pkgid/@stepName";
	public static  String dataFlagCmdb="data_cmdb_001";
	public static final int PeekFetchRows=5;
}
